backend:
  name: github # or gitlab, bitbucket
  repo: yourusername/yourrepo
  branch: main # or your default branch
  auth_endpoint: https://api.netlify.com

media_folder: "public/uploads" # Where images are stored
public_folder: "/uploads"

collections:
  - name: "events"
    label: "Events"
    folder: "src/content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Buy Ticket Link", name: "ticket_link", widget: "string" }
